---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kubernetes-csi/external-snapshotter/
  ref:
    tag: v5.0.1
  ignore: |
    # exclude all
    /*
    # include charts directory
    !client/config/crd
    !deploy/kubernetes/snapshot-controller
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-snapshotter-crd
  namespace: flux-system
spec:
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./client/config/crd"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
    namespace: flux-system
  path: "deploy/kubernetes/snapshot-controller"
  prune: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: snapshot-controller
    namespace: kube-system
