---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: csi-powermax
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dell/csi-powermax/
  ref:
    branch: v2.4.0
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-powermax
  namespace: flux-system
spec:
  interval: 5m
  releaseName: csi-powermax
  targetNamespace: powermax
  chart:
    spec:
# TODO validate that path works
      chart: helm/csi-powermax
      version: '2.4.0'
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: csi-powermax
        namespace: flux-system
      interval: 1m
# Original from :  https://github.com/dell/csi-powermax/blob/v2.3.0/helm/csi-powermax/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: csi-powermax-helm-values
    valuesKey: values.yaml
