# TODO bad practice, move outside git or encrypt : https://github.com/fluxcd/flux2-kustomize-helm-example#encrypt-kubernetes-secrets | https://fluxcd.io/docs/guides/mozilla-sops/
apiVersion: v1
kind: Secret
metadata:
  name: powermax-creds
  namespace: powermax
type: Opaque
data:
  username: c21j
  password: c21j

